### ISSUE TITLE
Add setup instructions to readme

### ISSUE THREAD

**Issue by jamestharpe** [Lyfen/lyfen-api#5]
I ran npm install then npm start, but I'm getting an error. If additional steps are needed, please put them in the readme.md.

Here's the output from npm start:

```
$ npm start

> mpv2@1.0.0 start C:\Users\james\code\lyfen-api
> nodemon lib/index.js --exec babel-node

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node lib/index.js`
module.js:471
    throw err;
    ^

Error: Cannot find module 'sequelize'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/Users/james/code/lyfen-api/lib/models/index.js:5:17)
    at Module._compile (module.js:570:32)
    at loader (C:\Users\james\code\lyfen-api\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\james\code\lyfen-api\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by grahamlutz** [comment]
Added sequelize to package.json and that should fix that issue.

**Comment by jamestharpe** [comment]
`npm install` now returns an error: 

```
npm ERR! Error: ENOENT: no such file or directory, chmod 'C:\Users\james\code\lyfen-api\node_modules\sequelize\node_modules\lodash\endsWith.js'
npm ERR!     at Error (native)
```
